-- Migration 009 Part 3: Remaining Core Topics
-- Adds blocks for: cheating_self, lust_vs_love, pretense, inauthenticity, marriage_strain, talking_stage, unclear, unlovable
-- Total: ~200 blocks

-- ============================================================================
-- CHEATING_SELF (Current: 7, Need: 23 more to reach 30)
-- Distribution: 6 reflection (3s1, 3s2), 6 normalization (3s1, 3s2), 7 exploration (4s1, 3s2), 4 reframe (s2)
-- ============================================================================

INSERT INTO amora_response_blocks (block_type, text, topics, emotions, stage, priority, active) VALUES

-- CHEATING_SELF - Reflection blocks (6)
('reflection', 'It sounds like you''re struggling with having cheated, and that internal conflict between what you did and who you want to be is really painful.', ARRAY['cheating_self', 'guilt', 'conflict'], ARRAY['guilty', 'confused'], 1, 50, true),
('reflection', 'When you''ve cheated, it can make you question your own character and whether you''re a good person, and that self-doubt is really hard to sit with.', ARRAY['cheating_self', 'self_doubt', 'character'], ARRAY['guilty', 'confused'], 2, 50, true),
('reflection', 'It sounds like part of you understands why you cheated but another part feels ashamed and confused about your choices, and that internal conflict is exhausting.', ARRAY['cheating_self', 'shame', 'conflict'], ARRAY['guilty', 'confused'], 2, 50, true),
('reflection', 'Cheating can make you question whether you''re capable of being faithful or whether there''s something fundamentally wrong with you, and those fears are really difficult.', ARRAY['cheating_self', 'self_doubt', 'fear'], ARRAY['worried', 'guilty'], 2, 50, true),
('reflection', 'It sounds like you''re trying to understand what led you to cheat, and that process of self-reflection can be both painful and necessary.', ARRAY['cheating_self', 'understanding', 'self_awareness'], ARRAY['reflective', 'guilty'], 2, 50, true),
('reflection', 'When you''ve hurt someone you care about through cheating, it can make you question whether you deserve forgiveness or another chance, and that uncertainty is really hard.', ARRAY['cheating_self', 'forgiveness', 'self_worth'], ARRAY['guilty', 'worried'], 2, 50, true),

-- CHEATING_SELF - Normalization blocks (6)
('normalization', 'Many people who cheat struggle with intense guilt and shame, and those feelings reflect that you care about the impact of your actions, even though you made a choice that hurt someone.', ARRAY['cheating_self', 'guilt', 'shame'], ARRAY['guilty', 'confused'], 1, 50, true),
('normalization', 'Cheating often happens when there are unmet needs or problems in the relationship that haven''t been addressed, and while that doesn''t excuse the cheating, it can help explain what led to it.', ARRAY['cheating_self', 'needs', 'understanding'], ARRAY['reflective', 'guilty'], 2, 50, true),
('normalization', 'It''s common for people who cheat to question their own character and whether they''re capable of being faithful, but one choice doesn''t define who you are. What matters is what you do with the awareness now.', ARRAY['cheating_self', 'character', 'growth'], ARRAY['hopeful', 'guilty'], 2, 50, true),
('normalization', 'Some people cheat because they''re trying to avoid difficult conversations or because they feel trapped in a relationship they don''t know how to leave. That doesn''t make it right, but it can help you understand what you need to address.', ARRAY['cheating_self', 'avoidance', 'needs'], ARRAY['reflective', 'guilty'], 2, 50, true),
('normalization', 'Feeling guilty about cheating shows that you have a conscience and that you care about the impact of your actions. That''s actually a sign of character, even though you made a choice that hurt someone.', ARRAY['cheating_self', 'guilt', 'character'], ARRAY['guilty', 'hopeful'], 2, 50, true),
('normalization', 'Working through having cheated often involves understanding why it happened, taking responsibility for the choice, and making different choices going forward. That process takes time and self-reflection.', ARRAY['cheating_self', 'responsibility', 'growth'], ARRAY['reflective', 'hopeful'], 2, 50, true),

-- CHEATING_SELF - Exploration blocks (7)
('exploration', 'What do you think led you to cheat? Was it unmet needs, problems in the relationship, something about yourself, or a combination?', ARRAY['cheating_self', 'understanding', 'self_awareness'], ARRAY['reflective', 'guilty'], 1, 50, true),
('exploration', 'How do you want to respond to having cheated? What would help you understand yourself better and make different choices?', ARRAY['cheating_self', 'growth', 'change'], ARRAY['reflective', 'determined'], 2, 50, true),
('exploration', 'What do you think you need to address to prevent this from happening again? Is it something about the relationship, something about yourself, or both?', ARRAY['cheating_self', 'needs', 'prevention'], ARRAY['reflective', 'determined'], 2, 50, true),
('exploration', 'If you could go back and handle things differently, what would you want to do instead of cheating?', ARRAY['cheating_self', 'reflection', 'growth'], ARRAY['reflective', 'regretful'], 2, 50, true),
('exploration', 'What would it look like to take responsibility for what happened while also understanding what led to it?', ARRAY['cheating_self', 'responsibility', 'understanding'], ARRAY['reflective', 'compassionate'], 2, 50, true),
('exploration', 'How do you want to move forward? What would help you rebuild trust if you stay, or what would help you learn and grow if you leave?', ARRAY['cheating_self', 'future', 'growth', 'healing'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('exploration', 'What would it mean to forgive yourself, and what would that process look like for you?', ARRAY['cheating_self', 'forgiveness', 'self_compassion'], ARRAY['reflective', 'compassionate'], 2, 50, true),

-- CHEATING_SELF - Reframe blocks (4)
('reframe', 'Cheating is a choice, and it''s important to take responsibility for that choice. But understanding why you made it can help you address what needs to be addressed—whether that''s unmet needs in the relationship, difficulty communicating, or patterns within yourself that you want to change. Taking responsibility doesn''t mean just feeling guilty; it means understanding what led to it and making different choices going forward.', ARRAY['cheating_self', 'responsibility', 'understanding', 'growth'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('reframe', 'One choice doesn''t define who you are as a person. Cheating was a choice you made, but it doesn''t mean you''re fundamentally unfaithful or that you can''t change. What matters is what you do with the awareness now—whether you take responsibility, understand what led to it, and commit to making different choices. People can and do change, but it requires honest self-reflection and a commitment to doing things differently.', ARRAY['cheating_self', 'character', 'growth', 'change'], ARRAY['hopeful', 'reflective'], 2, 50, true),
('reframe', 'If you want to rebuild trust after cheating, it will require consistent actions over time—transparency, accountability, and changed behavior. Words and apologies matter, but actions matter more. Your partner will need to see that you''re committed to understanding what led to the cheating and to making different choices. That process takes time and patience, and there''s no guarantee it will work, but it''s possible if both people are willing to do the work.', ARRAY['cheating_self', 'rebuilding', 'trust', 'actions'], ARRAY['hopeful', 'reflective'], 2, 50, true),
('reframe', 'Forgiving yourself after cheating doesn''t mean excusing what you did or minimizing the impact. It means acknowledging the choice, understanding what led to it, taking responsibility, and committing to growth. You can feel remorse and still work toward self-forgiveness. The goal isn''t to stop feeling guilty—it''s to use that guilt as motivation to understand yourself better and make different choices, while also recognizing that you''re human and capable of growth.', ARRAY['cheating_self', 'forgiveness', 'self_compassion', 'growth'], ARRAY['compassionate', 'reflective'], 2, 50, true),

-- ============================================================================
-- LUST_VS_LOVE (Current: 7, Need: 23 more to reach 30)
-- Distribution: 6 reflection (3s1, 3s2), 6 normalization (3s1, 3s2), 7 exploration (4s1, 3s2), 4 reframe (s2)
-- ============================================================================

-- LUST_VS_LOVE - Reflection blocks (6)
('reflection', 'It sounds like you''re trying to figure out whether what you feel is attraction, connection, or something deeper, and that confusion is really challenging.', ARRAY['lust_vs_love', 'confusion', 'feelings'], ARRAY['confused', 'curious'], 1, 50, true),
('reflection', 'When you''re trying to distinguish between lust and love, it can make you question your own feelings and whether you can trust what you''re experiencing.', ARRAY['lust_vs_love', 'trust', 'self_doubt'], ARRAY['confused', 'worried'], 2, 50, true),
('reflection', 'It sounds like part of you is drawn to the intensity and excitement, but another part wonders if there''s something more meaningful underneath, and that conflict is really difficult.', ARRAY['lust_vs_love', 'conflict', 'meaning'], ARRAY['confused', 'curious'], 2, 50, true),
('reflection', 'Trying to sort out lust from love can make you question whether your feelings are real or just physical attraction, and that uncertainty is really unsettling.', ARRAY['lust_vs_love', 'uncertainty', 'feelings'], ARRAY['confused', 'worried'], 2, 50, true),
('reflection', 'It sounds like you''re wondering if the intensity you feel is sustainable or if it''s just the excitement of something new, and that question is really important to explore.', ARRAY['lust_vs_love', 'intensity', 'sustainability'], ARRAY['curious', 'worried'], 2, 50, true),
('reflection', 'When physical attraction is strong, it can be hard to see whether there''s emotional connection underneath, and that confusion can make decisions feel really difficult.', ARRAY['lust_vs_love', 'attraction', 'connection'], ARRAY['confused', 'curious'], 2, 50, true),

-- LUST_VS_LOVE - Normalization blocks (6)
('normalization', 'Trying to figure out whether you feel lust or love is really common, especially in the early stages of a relationship or when physical attraction is strong. That confusion is normal and doesn''t mean you''re doing something wrong.', ARRAY['lust_vs_love', 'normal', 'common'], ARRAY['relieved', 'confused'], 1, 50, true),
('normalization', 'Lust and love aren''t mutually exclusive—you can feel both, and many healthy relationships have strong physical attraction alongside emotional connection. The question is whether there''s more than just the physical.', ARRAY['lust_vs_love', 'both', 'understanding'], ARRAY['relieved', 'confused'], 2, 50, true),
('normalization', 'It''s common to mistake intense physical attraction for love, especially when the chemistry is really strong. That intensity can feel like love, but love usually involves more than just attraction—it involves connection, care, and wanting the other person''s well-being.', ARRAY['lust_vs_love', 'intensity', 'understanding'], ARRAY['confused', 'reflective'], 2, 50, true),
('normalization', 'Some people find that physical attraction fades over time, and what''s left reveals whether there was real connection underneath. That process can be clarifying, even though it can also be disappointing if the attraction was all there was.', ARRAY['lust_vs_love', 'time', 'clarity'], ARRAY['reflective', 'worried'], 2, 50, true),
('normalization', 'It''s normal to question your feelings when you''re trying to distinguish between lust and love. That questioning shows you''re thinking critically about your experience, which is actually a good thing.', ARRAY['lust_vs_love', 'questioning', 'self_awareness'], ARRAY['reflective', 'confused'], 2, 50, true),
('normalization', 'Love often grows over time and deepens with connection, while lust can be more immediate and intense but may not deepen in the same way. Both are valid experiences, but they serve different purposes in relationships.', ARRAY['lust_vs_love', 'understanding', 'time'], ARRAY['reflective', 'confused'], 2, 50, true),

-- LUST_VS_LOVE - Exploration blocks (7)
('exploration', 'When you think about this person, what comes up for you? Physical attraction, emotional connection, care for their well-being, or a combination?', ARRAY['lust_vs_love', 'feelings', 'awareness'], ARRAY['reflective', 'curious'], 1, 50, true),
('exploration', 'What do you think you''d feel if the physical attraction faded? Would there still be something meaningful there?', ARRAY['lust_vs_love', 'sustainability', 'meaning'], ARRAY['reflective', 'curious'], 2, 50, true),
('exploration', 'How do you feel when you''re not with this person? Do you miss them, think about them, care about their life, or is it more about the physical connection?', ARRAY['lust_vs_love', 'connection', 'feelings'], ARRAY['reflective', 'curious'], 2, 50, true),
('exploration', 'What would it look like if this were love? What would be different from what you''re experiencing now?', ARRAY['lust_vs_love', 'vision', 'understanding'], ARRAY['reflective', 'curious'], 2, 50, true),
('exploration', 'How has this experience changed how you think about attraction, connection, and what you want in relationships?', ARRAY['lust_vs_love', 'growth', 'understanding'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('exploration', 'What do you think you need to figure out to feel clear about what this is? Time, more connection, something else?', ARRAY['lust_vs_love', 'clarity', 'needs'], ARRAY['reflective', 'confused'], 2, 50, true),
('exploration', 'If you could give yourself advice about this situation, what would you want to remember?', ARRAY['lust_vs_love', 'wisdom', 'self'], ARRAY['compassionate', 'reflective'], 2, 50, true),

-- LUST_VS_LOVE - Reframe blocks (4)
('reframe', 'Lust and love can coexist, and many healthy relationships have both strong physical attraction and deep emotional connection. The question isn''t whether you feel lust—it''s whether there''s more than just lust. Love usually involves wanting the other person''s well-being, caring about them as a person, and feeling connected beyond just the physical. If you find yourself thinking about them when you''re apart, caring about their life and feelings, and wanting to support them, that''s often a sign there''s more than just attraction.', ARRAY['lust_vs_love', 'understanding', 'connection'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('reframe', 'Physical attraction is often immediate and intense, while love tends to grow over time as you get to know someone and build connection. If what you''re feeling is mostly about the physical and the excitement, it might be lust. But if you find yourself wanting to know them deeper, caring about their well-being, and feeling connected even when you''re not together, that''s often a sign of something more. Time and deeper connection can help clarify what you''re really feeling.', ARRAY['lust_vs_love', 'time', 'connection', 'clarity'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('reframe', 'There''s nothing wrong with feeling lust or strong physical attraction—it''s a normal and valid part of human experience. The question is whether you want more than just that. If you''re looking for a deeper connection, then it''s worth exploring whether that''s possible with this person. But if you''re okay with just the physical connection and that''s what both people want, that''s also valid. What matters is being honest with yourself and the other person about what you want and what you''re experiencing.', ARRAY['lust_vs_love', 'honesty', 'needs', 'validity'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('reframe', 'Sometimes the intensity of physical attraction can make it hard to see whether there''s emotional connection underneath. If you''re unsure, it can help to spend time together doing things that aren''t just physical—talking, sharing experiences, getting to know each other as people. That can reveal whether there''s real connection or if it''s mostly about the attraction. Love usually deepens with connection and time, while lust may stay intense but not necessarily deepen in the same way.', ARRAY['lust_vs_love', 'connection', 'time', 'clarity'], ARRAY['reflective', 'hopeful'], 2, 50, true);

-- ============================================================================
-- Note: Continuing with remaining topics in next file due to length
-- Remaining: pretense, inauthenticity, marriage_strain, talking_stage, unclear, unlovable
-- ============================================================================
