-- Migration 009 Part 3 Final: Last 4 Topics
-- Adds blocks for: marriage_strain, talking_stage, unclear, unlovable
-- Continues from 009_expand_core_topics_PART3_continued.sql

-- ============================================================================
-- MARRIAGE_STRAIN (Current: 5, Need: 25 more to reach 30)
-- Distribution: 7 reflection (4s1, 3s2), 7 normalization (4s1, 3s2), 7 exploration (4s1, 3s2), 4 reframe (s2)
-- ============================================================================

INSERT INTO amora_response_blocks (block_type, text, topics, emotions, stage, priority, active) VALUES

-- MARRIAGE_STRAIN - Reflection blocks (7)
('reflection', 'It sounds like your marriage is going through a really difficult time right now, and that strain is taking a toll on both of you.', ARRAY['marriage_strain', 'difficulty', 'stress'], ARRAY['stressed', 'tired'], 1, 50, true),
('reflection', 'When a marriage is strained, it can make you question whether you can fix things or if it''s time to consider other options, and that uncertainty is really hard.', ARRAY['marriage_strain', 'uncertainty', 'decision'], ARRAY['worried', 'confused'], 2, 50, true),
('reflection', 'It sounds like the strain in your marriage is affecting not just your relationship, but how you see yourself and your future, and that impact is really significant.', ARRAY['marriage_strain', 'self', 'future'], ARRAY['worried', 'sad'], 2, 50, true),
('reflection', 'Marriage strain often makes you feel like you''re failing or that you should be able to fix things, and that pressure can make the situation feel even harder.', ARRAY['marriage_strain', 'pressure', 'failure'], ARRAY['stressed', 'sad'], 2, 50, true),
('reflection', 'It sounds like you and your spouse are both struggling, but maybe in different ways, and that disconnect can make it hard to support each other.', ARRAY['marriage_strain', 'disconnect', 'support'], ARRAY['lonely', 'sad'], 2, 50, true),
('reflection', 'When a marriage is strained, it can make you wonder if the love is still there or if you''re just going through the motions, and that question is really painful.', ARRAY['marriage_strain', 'love', 'uncertainty'], ARRAY['sad', 'worried'], 2, 50, true),
('reflection', 'It sounds like the strain has been building over time, and now it feels overwhelming, like you don''t know where to start to make things better.', ARRAY['marriage_strain', 'overwhelm', 'hope'], ARRAY['overwhelmed', 'hopeless'], 2, 50, true),

-- MARRIAGE_STRAIN - Normalization blocks (7)
('normalization', 'Marriage strain is really common, especially during difficult life transitions, stress, or when couples have grown apart over time. You''re not alone in experiencing this.', ARRAY['marriage_strain', 'normal', 'common'], ARRAY['relieved', 'stressed'], 1, 50, true),
('normalization', 'It''s normal for marriages to go through difficult periods, and experiencing strain doesn''t mean your marriage is doomed. Many couples work through challenging times and come out stronger.', ARRAY['marriage_strain', 'normal', 'hope'], ARRAY['hopeful', 'stressed'], 2, 50, true),
('normalization', 'Marriage strain often happens when both people are struggling with their own issues or when life stressors pile up. That doesn''t mean the marriage is the problem—it might mean you both need support.', ARRAY['marriage_strain', 'stress', 'support'], ARRAY['stressed', 'hopeful'], 2, 50, true),
('normalization', 'It''s common to feel like you should be able to fix things on your own, but marriage strain often requires both people to be willing to work on things, and sometimes outside help can make a big difference.', ARRAY['marriage_strain', 'help', 'support'], ARRAY['hopeful', 'stressed'], 2, 50, true),
('normalization', 'Some marriages go through periods where the connection feels distant or strained, and that can be really painful. But distance doesn''t always mean the end—sometimes it means you need to find new ways to connect.', ARRAY['marriage_strain', 'distance', 'connection'], ARRAY['sad', 'hopeful'], 2, 50, true),
('normalization', 'It''s normal to question your marriage when things are strained, and to wonder if you should stay or go. Those questions are valid, and there''s no right answer that applies to everyone.', ARRAY['marriage_strain', 'decision', 'uncertainty'], ARRAY['confused', 'worried'], 2, 50, true),
('normalization', 'Marriage strain can make you feel like you''re failing, but struggling in a relationship doesn''t mean you''re a failure. Relationships are complex, and sometimes they need attention and work to thrive.', ARRAY['marriage_strain', 'failure', 'understanding'], ARRAY['relieved', 'hopeful'], 2, 50, true),

-- MARRIAGE_STRAIN - Exploration blocks (7)
('exploration', 'What do you think is causing the strain in your marriage? Is it specific issues, life stress, growing apart, or something else?', ARRAY['marriage_strain', 'causes', 'awareness'], ARRAY['reflective', 'stressed'], 1, 50, true),
('exploration', 'How has the strain affected how you see your marriage or your future together?', ARRAY['marriage_strain', 'perspective', 'future'], ARRAY['reflective', 'worried'], 2, 50, true),
('exploration', 'What do you think you and your spouse need to work through this? Communication, support, time, something else?', ARRAY['marriage_strain', 'needs', 'support'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('exploration', 'What would it look like if things got better? What would need to change?', ARRAY['marriage_strain', 'vision', 'change'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('exploration', 'How do you want to approach this? Do you want to work on things together, or do you need to figure out what you want first?', ARRAY['marriage_strain', 'approach', 'decision'], ARRAY['reflective', 'confused'], 2, 50, true),
('exploration', 'What support do you think you need right now? From your spouse, from others, or from yourself?', ARRAY['marriage_strain', 'needs', 'support'], ARRAY['reflective', 'tired'], 2, 50, true),
('exploration', 'If you could give yourself advice about this marriage strain, what would you want to remember?', ARRAY['marriage_strain', 'wisdom', 'self'], ARRAY['compassionate', 'reflective'], 2, 50, true),

-- MARRIAGE_STRAIN - Reframe blocks (4)
('reframe', 'Marriage strain often happens when couples have grown apart, when life stressors pile up, or when unresolved issues accumulate over time. It doesn''t necessarily mean the marriage is over—it might mean you need to find new ways to connect, to communicate, or to support each other. Many couples work through difficult periods and come out stronger, but it usually requires both people to be willing to do the work and sometimes to get outside help.', ARRAY['marriage_strain', 'growth', 'connection', 'support'], ARRAY['hopeful', 'reflective'], 2, 50, true),
('reframe', 'When a marriage is strained, it''s common to feel like you should be able to fix it on your own, but marriage is a partnership, and it takes both people to make it work. If you''re the only one trying, that''s information. But if both of you are willing to work on things, there''s often hope. Sometimes that means couples therapy, sometimes it means finding new ways to connect, and sometimes it means addressing individual issues that are affecting the relationship.', ARRAY['marriage_strain', 'partnership', 'work', 'hope'], ARRAY['hopeful', 'reflective'], 2, 50, true),
('reframe', 'Marriage strain can make you question whether you should stay or go, and there''s no one right answer. Some marriages can be repaired with work and commitment from both people. Others have run their course, and ending them is the healthiest choice. What matters is being honest with yourself about what you need, what you''re willing to work on, and whether your spouse is willing to do the same. There''s no shame in either choice—staying and working on things, or leaving if that''s what''s right for you.', ARRAY['marriage_strain', 'decision', 'honesty', 'self'], ARRAY['reflective', 'compassionate'], 2, 50, true),
('reframe', 'Sometimes marriage strain is a sign that the relationship needs attention and work, not that it''s doomed. But it''s also okay to recognize when a marriage has run its course and when staying would mean sacrificing your own well-being. The decision to stay or leave is deeply personal, and there''s no right answer that applies to everyone. What matters is being honest with yourself about what you need and what''s possible, and making choices that honor your own well-being while also considering the impact on your spouse and any children involved.', ARRAY['marriage_strain', 'decision', 'wellbeing', 'honesty'], ARRAY['reflective', 'compassionate'], 2, 50, true),

-- ============================================================================
-- TALKING_STAGE (Current: 4, Need: 26 more to reach 30)
-- Distribution: 7 reflection (4s1, 3s2), 7 normalization (4s1, 3s2), 8 exploration (4s1, 4s2), 4 reframe (s2)
-- ============================================================================

-- TALKING_STAGE - Reflection blocks (7)
('reflection', 'It sounds like you''re in the talking stage and things feel unclear about where this is heading, and that ambiguity is really hard to sit with.', ARRAY['talking_stage', 'unclear', 'ambiguity'], ARRAY['confused', 'frustrated'], 1, 50, true),
('reflection', 'Being in the talking stage can make you feel like you''re in limbo, not knowing if this will turn into something more or if it''s just casual, and that uncertainty is exhausting.', ARRAY['talking_stage', 'limbo', 'uncertainty'], ARRAY['confused', 'tired'], 2, 50, true),
('reflection', 'It sounds like part of you wants to know where things stand, but another part might be afraid of what that clarity might mean, and that conflict is really difficult.', ARRAY['talking_stage', 'clarity', 'fear'], ARRAY['confused', 'worried'], 2, 50, true),
('reflection', 'The talking stage often makes you question whether you''re allowed to want more or ask for clarity, and that uncertainty about your own needs is really challenging.', ARRAY['talking_stage', 'needs', 'uncertainty'], ARRAY['confused', 'frustrated'], 2, 50, true),
('reflection', 'It sounds like you''re investing time and energy into something that doesn''t have clear boundaries or commitment, and that can feel both exciting and scary.', ARRAY['talking_stage', 'investment', 'boundaries'], ARRAY['confused', 'worried'], 2, 50, true),
('reflection', 'When you''re in the talking stage, it can be hard to know what you''re allowed to expect or ask for, and that confusion about boundaries is really difficult.', ARRAY['talking_stage', 'boundaries', 'expectations'], ARRAY['confused', 'frustrated'], 2, 50, true),
('reflection', 'It sounds like the talking stage is bringing up questions about your worth and whether you''re enough for someone to want to move forward with, and those doubts can be really painful.', ARRAY['talking_stage', 'self_worth', 'doubt'], ARRAY['hurt', 'worried'], 2, 50, true),

-- TALKING_STAGE - Normalization blocks (7)
('normalization', 'The talking stage is really common in modern dating, and being in one doesn''t mean you''re doing something wrong. Many people find themselves in this undefined space.', ARRAY['talking_stage', 'normal', 'common'], ARRAY['relieved', 'confused'], 1, 50, true),
('normalization', 'It''s normal to feel confused or frustrated in the talking stage, especially if you want more clarity or commitment than the other person seems willing to give. Those feelings are valid.', ARRAY['talking_stage', 'needs', 'frustration'], ARRAY['frustrated', 'confused'], 2, 50, true),
('normalization', 'Many people stay in the talking stage because they''re afraid that asking for clarity will end things, but the uncertainty can be just as painful as a potential rejection. Both are hard, but at least clarity gives you information.', ARRAY['talking_stage', 'fear', 'clarity'], ARRAY['worried', 'reflective'], 2, 50, true),
('normalization', 'It''s common to feel like you''re not allowed to want more from the talking stage, or that asking for commitment means you''re being "too much." But wanting clarity and commitment isn''t too much—it''s a valid need.', ARRAY['talking_stage', 'needs', 'self_worth'], ARRAY['hurt', 'determined'], 2, 50, true),
('normalization', 'Some people stay in the talking stage because they''re getting some of what they need—connection, attention, hope—even if it''s not everything. That can make it hard to leave, even when you know it''s not enough.', ARRAY['talking_stage', 'needs', 'attachment'], ARRAY['confused', 'hurt'], 2, 50, true),
('normalization', 'The talking stage often continues because both people are getting something from the ambiguity—maybe one person gets the benefits without commitment, and the other gets hope without having to face rejection. But that dynamic can be painful for the person who wants more.', ARRAY['talking_stage', 'dynamics', 'needs'], ARRAY['hurt', 'reflective'], 2, 50, true),
('normalization', 'It''s normal to question whether the talking stage will turn into something more, and that uncertainty can make it hard to know how to proceed or what to invest.', ARRAY['talking_stage', 'uncertainty', 'investment'], ARRAY['confused', 'worried'], 2, 50, true),

-- TALKING_STAGE - Exploration blocks (8)
('exploration', 'What do you want from this talking stage? Clarity, commitment, to see where it goes, or something else?', ARRAY['talking_stage', 'needs', 'clarity'], ARRAY['reflective', 'confused'], 1, 50, true),
('exploration', 'What makes it hard to ask for what you want? Fear of rejection, fear of ending things, or something else?', ARRAY['talking_stage', 'fear', 'needs'], ARRAY['worried', 'reflective'], 2, 50, true),
('exploration', 'How is this talking stage meeting your needs, and how is it not?', ARRAY['talking_stage', 'needs', 'awareness'], ARRAY['reflective', 'confused'], 2, 50, true),
('exploration', 'If you could have a conversation about where things stand, what would you want to say?', ARRAY['talking_stage', 'communication', 'needs'], ARRAY['reflective', 'determined'], 2, 50, true),
('exploration', 'What would you need to feel good about continuing in the talking stage, or what would help you decide to move on?', ARRAY['talking_stage', 'needs', 'decision'], ARRAY['reflective', 'confused'], 2, 50, true),
('exploration', 'How has being in the talking stage affected how you see yourself or what you want in relationships?', ARRAY['talking_stage', 'self', 'growth'], ARRAY['reflective', 'hopeful'], 2, 50, true),
('exploration', 'What boundaries do you want to set for yourself in the talking stage?', ARRAY['talking_stage', 'boundaries', 'self'], ARRAY['reflective', 'determined'], 2, 50, true),
('exploration', 'If you could give yourself advice about the talking stage, what would you want to remember?', ARRAY['talking_stage', 'wisdom', 'self'], ARRAY['compassionate', 'reflective'], 2, 50, true),

-- TALKING_STAGE - Reframe blocks (4)
('reframe', 'The talking stage can work for some people who want connection without commitment, but it''s painful when one person wants more than the other is willing to give. If you''re in the talking stage and it''s causing you pain, that''s information. You''re allowed to want clarity and commitment, and you''re allowed to express those needs. If the other person can''t meet them, that doesn''t mean you''re too much—it means you''re not compatible in what you want right now.', ARRAY['talking_stage', 'needs', 'self_worth', 'compatibility'], ARRAY['reflective', 'determined'], 2, 50, true),
('reframe', 'Staying in the talking stage when you want more often comes from a fear of being alone or a fear of rejection, but the uncertainty and lack of clarity can be just as painful as those fears. At least with clarity, you have information to make decisions. Staying in ambiguity because you''re afraid of the answer often means staying in pain because you''re afraid of a different kind of pain.', ARRAY['talking_stage', 'fear', 'clarity', 'pain'], ARRAY['reflective', 'compassionate'], 2, 50, true),
('reframe', 'You deserve to be with someone who wants to be with you in the way you want to be with them. If you want commitment and clarity, you''re allowed to ask for that. If the other person can''t give it, that''s their choice, but it doesn''t mean you should settle for less than what you need. Your needs are valid, and you don''t have to apologize for wanting clarity or commitment.', ARRAY['talking_stage', 'needs', 'self_worth', 'boundaries'], ARRAY['determined', 'reflective'], 2, 50, true),
('reframe', 'Sometimes the talking stage continues because both people are avoiding having a difficult conversation about what they want. But avoiding that conversation doesn''t make the uncertainty go away—it just prolongs it. Having the conversation, even if it leads to an ending, gives you clarity and the ability to move forward, whether that''s together with commitment or apart so you can find someone who wants what you want.', ARRAY['talking_stage', 'communication', 'clarity', 'growth'], ARRAY['hopeful', 'reflective'], 2, 50, true);

-- ============================================================================
-- Note: Continuing with unclear and unlovable in next file
-- ============================================================================
