# Quick script to remind how to check Render logs

Write-Host "========================================"
Write-Host " HOW TO CHECK RENDER LOGS"
Write-Host "========================================"
Write-Host ""
Write-Host "1. Go to: https://dashboard.render.com/"
Write-Host "2. Click on your 'macthiq-ai-backend' service"
Write-Host "3. Click on the 'Logs' tab"
Write-Host "4. Look for recent entries with:"
Write-Host "   - 'Amora request from user'"
Write-Host "   - 'Amora Blocks Service response'"
Write-Host "   - 'Selected blocks:'"
Write-Host "   - Any ERROR or WARNING messages"
Write-Host ""
Write-Host "5. Check specifically for:"
Write-Host "   - Block selection queries"
Write-Host "   - Embedding similarity scores"
Write-Host "   - Final assembled response"
Write-Host ""
Write-Host "If you see errors, copy them and we'll fix them!"
Write-Host ""
Write-Host "========================================"
